const express=require('express'),http=require('http'),{Server}=require('socket.io'),path=require('path');
const app=express(),server=http.createServer(app),io=new Server(server),PORT=process.env.PORT||3000;app.use(express.static(__dirname));;
const Q=[
{p:1,t:'Aquecimento — Leitura',type:'bar',d:{l:['Seg','Ter','Qua','Qui'],v:[10,15,8,12]},q:'Em qual dia a quantidade foi maior?',o:['Segunda','Terça','Quarta','Quinta'],a:1,pts:100},
{p:1,t:'Aquecimento — Comparando',type:'bar',d:{l:['A','B','C','D'],v:[12,7,15,10]},q:'Qual categoria apresenta o menor valor?',o:['A','B','C','D'],a:1,pts:100},
{p:2,t:'Investigação — Linhas',type:'line',d:{l:['1ª','2ª','3ª','4ª','5ª'],v:[20,25,23,30,28]},q:'Entre quais semanas ocorreu o maior aumento?',o:['1ª → 2ª','2ª → 3ª','3ª → 4ª','4ª → 5ª'],a:2,pts:150},
{p:2,t:'Investigação — Maior valor',type:'line',d:{l:['Jan','Fev','Mar','Abr'],v:[40,35,50,45]},q:'Em qual mês o valor foi maior?',o:['Janeiro','Fevereiro','Março','Abril'],a:2,pts:150},
{p:3,t:'Desafio — Setores',type:'pie',d:{l:['Futebol','Vôlei','Basquete','Outros'],v:[40,25,20,15]},q:'Qual categoria representa 40%?',o:['Futebol','Vôlei','Basquete','Outros'],a:0,pts:200},
{p:3,t:'Desafio — Porcentagem',type:'bar',d:{l:['A','B','C'],v:[20,30,50]},q:'Se o gráfico representa 100 alunos, quantos pertencem à categoria C?',o:['20','30','40','50'],a:3,pts:200},
{p:4,t:'CHEFÃO — Interpretação',type:'line',d:{l:['Seg','Ter','Qua','Qui','Sex'],v:[50,60,55,75,70]},q:'Qual afirmação está correta?',o:['Quarta foi o maior valor.','Quinta foi o maior valor.','Sexta foi menor que terça.','Segunda foi maior que quinta.'],a:1,pts:300}
];
const rooms=new Map();function code(){let c;do c=''+Math.floor(100000+Math.random()*900000);while(rooms.has(c));return c}function pub(r){return{code:r.code,started:r.started,players:[...r.players.values()].map(x=>({id:x.id,name:x.name,score:x.score}))}}function sendQ(r){let q=Q[r.i];if(!q)return finish(r);r.startedAt=Date.now();io.to(r.code).emit('question',{index:r.i,total:Q.length,phase:q.p,title:q.t,type:q.type,data:q.d,question:q.q,options:q.o,duration:90})}function finish(r){r.finished=true;io.to(r.code).emit('finished',{ranking:[...r.players.values()].sort((a,b)=>b.score-a.score).map(x=>({name:x.name,score:x.score}))})}
io.on('connection',s=>{s.on('create',({name})=>{let c=code(),r={code:c,host:s.id,started:false,finished:false,i:0,startedAt:0,players:new Map};r.players.set(s.id,{id:s.id,name:name||'Professor',score:0});rooms.set(c,r);s.join(c);s.emit('created',{code:c});io.to(c).emit('room',pub(r))});s.on('join',({code,name})=>{let r=rooms.get(String(code||'').trim());if(!r)return s.emit('err','Sala não encontrada.');if(r.started)return s.emit('err','O jogo já começou.');r.players.set(s.id,{id:s.id,name:String(name||'Aluno').slice(0,30),score:0});s.join(r.code);s.emit('joined',{code:r.code});io.to(r.code).emit('room',pub(r))});s.on('start',({code})=>{let r=rooms.get(code);if(!r||r.host!==s.id)return;r.started=true;r.i=0;io.to(r.code).emit('room',pub(r));sendQ(r)});s.on('answer',({code,answer})=>{let r=rooms.get(code),p=r&&r.players.get(s.id),q=r&&Q[r.i];if(!r||!p||!q||p.answered)return;p.answered=true;let ok=+answer===q.a&&Date.now()-r.startedAt<=90000;if(ok){let bonus=Math.max(0,Math.round((90000-(Date.now()-r.startedAt))/1000*2));p.score+=q.pts+bonus}s.emit('result',{ok,gained:ok?q.pts:0});io.to(r.code).emit('room',pub(r))});s.on('next',({code})=>{let r=rooms.get(code);if(!r||r.host!==s.id)return;r.i++;r.players.forEach(p=>p.answered=false);sendQ(r)});s.on('disconnect',()=>{for(let r of rooms.values())if(r.players.delete(s.id)){if(r.host===s.id){let n=r.players.values().next().value;r.host=n?.id||null}if(r.players.size)io.to(r.code).emit('room',pub(r));else rooms.delete(r.code)}})});
server.listen(PORT,()=>console.log('running '+PORT));
